name: Build and Release

permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Go Binaries for Multiple OS/ARCH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binaries
        run: |
          mkdir -p dist
          export CGO_ENABLED=0

          # Linux amd64
          GOOS=linux GOARCH=amd64 go build -a -ldflags '-w -s' -o dist/vcd-vm-extraconfig-linux-amd64 ./vcd-vm-extraconfig.go

          # macOS amd64
          GOOS=darwin GOARCH=amd64 go build -a -ldflags '-w -s' -o dist/vcd-vm-extraconfig-darwin-amd64 ./vcd-vm-extraconfig.go

          # macOS arm64
          GOOS=darwin GOARCH=arm64 go build -a -ldflags '-w -s' -o dist/vcd-vm-extraconfig-darwin-arm64 ./vcd-vm-extraconfig.go

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          draft: false
          fail_on_unmatched_files: true
